{% set name = "pyleco" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymeasure/pyleco/archive/refs/tags/v{{ version }}-cf.tar.gz
  sha256: a04a01e7a677dfd9f0e644cc712d80df1790b136b06c0bfec9be93590fd0357b

build:
  noarch: python
  entry_points:
    - coordinator = pyleco.coordinators.coordinator:main
    - proxy_server = pyleco.coordinators.proxy_server:main
    - starter = pyleco.management.starter:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - pyzmq >=22.3.0
    - uuid6 >=2024.1.12

test:
  imports:
    - pyleco
  commands:
    - coordinator --help
    - proxy_server --help
    - starter --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pymeasure/pyleco
  summary: Python reference implementation of the Laboratory Experiment COntrol (LECO) protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenediktBurger
