{% set name = "pyleco" %}
{% set version = "0.6.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymeasure/pyleco/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 422203e14ff6d79fca482b6782778d6480c6a8ae847ce65a153727537e3cb8ff

build:
  noarch: python
  entry_points:
    - coordinator = pyleco.coordinators.coordinator:main
    - proxy_server = pyleco.coordinators.proxy_server:main
    - starter = pyleco.management.starter:main
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - pyzmq >=22.3.0
    - uuid6 >=2024.1.12

test:
  imports:
    - pyleco
  commands:
    - coordinator --help
    - proxy_server --help
    - starter --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pymeasure/pyleco
  summary: Python reference implementation of the Laboratory Experiment COntrol (LECO) protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenediktBurger
